#!/usr/bin/env python3
"""
Curate a diverse subset of 15–20 test images for benchmarking.

Selects images spanning multiple writers (where identifiable), varying text
density, contrast, and estimated line counts.  Uses the dataset manifest
generated by scripts/download_essay_samples.py.

Output:
    benchmark/test_dataset/curated/          — symlinks to selected images
    benchmark/test_dataset/curated_manifest.json — subset metadata

Usage:
    python scripts/curate_test_subset.py
    python scripts/curate_test_subset.py --count 20
    python scripts/curate_test_subset.py --manual   # interactive selection
"""

from __future__ import annotations

import json
import random
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TEST_DATASET = PROJECT_ROOT / "benchmark" / "test_dataset"
MANIFEST_PATH = TEST_DATASET / "dataset_manifest.json"
CURATED_DIR = TEST_DATASET / "curated"
CURATED_MANIFEST = TEST_DATASET / "curated_manifest.json"

DEFAULT_SUBSET_SIZE = 20


# ---------------------------------------------------------------------------
# Diversity scoring
# ---------------------------------------------------------------------------

def diversity_score(entries: list[dict[str, Any]], target_size: int) -> list[dict[str, Any]]:
    """
    Select a diverse subset using stratified sampling across:
      - Text density (low / medium / high)
      - Estimated line count (short / medium / long)
      - Contrast (low / medium / high)
    """
    if len(entries) <= target_size:
        return entries

    # Compute tertiles for each feature
    def _tertile(values: list[float]) -> tuple[float, float]:
        sorted_vals = sorted(values)
        n = len(sorted_vals)
        return sorted_vals[n // 3], sorted_vals[2 * n // 3]

    densities = [e.get("text_density", 0) for e in entries]
    lines = [e.get("estimated_lines", 0) for e in entries]
    contrasts = [e.get("contrast", 0) for e in entries]

    d_low, d_high = _tertile(densities)
    l_low, l_high = _tertile(lines)
    c_low, c_high = _tertile(contrasts)

    # Assign each entry to a bucket
    buckets: dict[str, list[dict[str, Any]]] = {}
    for e in entries:
        d = "H" if e.get("text_density", 0) >= d_high else ("L" if e.get("text_density", 0) <= d_low else "M")
        l = "H" if e.get("estimated_lines", 0) >= l_high else ("L" if e.get("estimated_lines", 0) <= l_low else "M")
        c = "H" if e.get("contrast", 0) >= c_high else ("L" if e.get("contrast", 0) <= c_low else "M")
        key = f"d{d}_l{l}_c{c}"
        buckets.setdefault(key, []).append(e)

    # Sample proportionally from each bucket
    selected: list[dict[str, Any]] = []
    rng = random.Random(42)  # Deterministic

    # Ensure at least 1 from each non-empty bucket
    bucket_keys = sorted(buckets.keys())
    for key in bucket_keys:
        if buckets[key]:
            selected.append(rng.choice(buckets[key]))

    # Fill remaining slots
    remaining = target_size - len(selected)
    if remaining > 0:
        pool = [e for e in entries if e not in selected]
        rng.shuffle(pool)
        selected.extend(pool[:remaining])

    return selected[:target_size]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Curate diverse test image subset.")
    parser.add_argument("--count", type=int, default=DEFAULT_SUBSET_SIZE,
                        help=f"Number of images to select (default: {DEFAULT_SUBSET_SIZE})")
    parser.add_argument("--manual", action="store_true",
                        help="Interactive manual selection (not yet implemented)")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed for reproducibility")
    args = parser.parse_args()

    if args.manual:
        print("Manual selection mode not yet implemented. Use --count instead.")
        sys.exit(1)

    random.seed(args.seed)

    # Load manifest
    if not MANIFEST_PATH.exists():
        print(f"ERROR: Manifest not found at {MANIFEST_PATH}")
        print("Run scripts/download_essay_samples.py first.")
        sys.exit(1)

    manifest = json.loads(MANIFEST_PATH.read_text())
    print(f"Loaded manifest with {len(manifest)} images.")

    # Select diverse subset
    selected = diversity_score(manifest, args.count)
    print(f"Selected {len(selected)} diverse images.")

    # Write curated manifest
    curated_meta = []
    for entry in selected:
        curated_meta.append({
            "image": entry["image"],
            "path": entry["path"],
            "text_density": entry.get("text_density", 0),
            "estimated_lines": entry.get("estimated_lines", 0),
            "contrast": entry.get("contrast", 0),
        })

    CURATED_MANIFEST.write_text(json.dumps(curated_meta, indent=2))
    print(f"  Curated manifest → {CURATED_MANIFEST}")

    # Create symlinks
    CURATED_DIR.mkdir(parents=True, exist_ok=True)
    for entry in selected:
        src = TEST_DATASET / entry["image"]
        dst = CURATED_DIR / entry["image"]
        if not dst.exists():
            dst.symlink_to(src.resolve())
            print(f"  {entry['image']}")

    print()
    print("Done.  Curated subset ready in benchmark/test_dataset/curated/")
    print(f"  {len(selected)} images selected across diverse features.")
    print()
    print("Next: scripts/generate_ground_truth.py")


if __name__ == "__main__":
    main()
